In [49]:
import numpy as np
import pandas as pd

In [50]:
df=pd.read_csv("transactionsd.csv")

handling categorical data

In [51]:
df=pd.DataFrame({
    'colour':['red','blue','green','red','green']
})
df

  colour
0    red
1   blue
2  green
3    red
4  green

In [52]:
df['colour']=df['colour'].astype('category')
df

  colour
0    red
1   blue
2  green
3    red
4  green

In [53]:
df.dtypes

colour    category
dtype: object

In [54]:
sizes=pd.Categorical(['s','m','l','s','m','m','s','l'],categories=['s','m','l'],ordered=True)

In [55]:
df_grades=pd.DataFrame({'grade':['a','b','a','c','b','a']})

In [56]:
df_grades.value_counts()

grade
a        3
b        2
c        1
Name: count, dtype: int64

In [57]:
df=pd.DataFrame({
    'city':['delhi','mumbai','delhi','mumbai','delhi'],
    'salse':[200,150,300,400,250]
})

In [58]:
df=pd.DataFrame({
    'size':['m','s','l','m'],
    'item':['shirt','pants','shirt','pants']
})

In [59]:
df['sizes']=pd.Categorical(df['size'],categories=['s','l','m'],ordered=True)

In [60]:
df['sizes']>'m'

0    False
1    False
2    False
3    False
Name: sizes, dtype: bool

In [61]:
df['is_large']=df['sizes']

In [62]:
# df[df['size'>'m']]

In [63]:
# df[df['size'=='l']]

In [64]:
# df[df['size'<'s']]

In [65]:
# ndf=df['size'].cat.rename_categories({'s':'small','m':'medium','l':'large'})

In [66]:

employees = pd.DataFrame({
    'name': ['John', 'Charlie', 'David', 'Ben', 'Sara', 'Ravi', 'Neena', 'Amit', 'John', 'Rita'],
    'age': [28, 32, 45, 29, 31, 40, 27, 36, 33, 30],
    'salary': [45000, 52000, 72000, 50000, 48000, 65000, 41000, 58000, 60000, 55000],
    'department': ['HR', 'HR', 'Finance', 'IT', 'IT', 'Finance', 'HR', 'Engineering', 'Engineering', 'IT'],
    'gender': ['male', 'male', 'male', 'male', 'female', 'male', 'female', 'male', 'male', 'female']
})

employees

      name  age  salary   department  gender
0     John   28   45000           HR    male
1  Charlie   32   52000           HR    male
2    David   45   72000      Finance    male
3      Ben   29   50000           IT    male
4     Sara   31   48000           IT  female
5     Ravi   40   65000      Finance    male
6    Neena   27   41000           HR  female
7     Amit   36   58000  Engineering    male
8     John   33   60000  Engineering    male
9     Rita   30   55000           IT  female

In [67]:
pd.get_dummies(employees,columns=['gender'])

      name  age  salary   department  gender_female  gender_male
0     John   28   45000           HR          False         True
1  Charlie   32   52000           HR          False         True
2    David   45   72000      Finance          False         True
3      Ben   29   50000           IT          False         True
4     Sara   31   48000           IT           True        False
5     Ravi   40   65000      Finance          False         True
6    Neena   27   41000           HR           True        False
7     Amit   36   58000  Engineering          False         True
8     John   33   60000  Engineering          False         True
9     Rita   30   55000           IT           True        False